version: '3'
services:
    db:
        image: mariadb
        container_name: mariadb
        ports:
          - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'storage:/var/lib/mysql'
        networks:
            - nw
networks:
    nw:
        driver: bridge
volumes:
    storage:
        driver: local
